### 킹, 퀸, 룩, 비숍, 나이트, 폰
동혁이는 오래된 창고를 뒤지다가 낡은 체스판과 피스를 발견했다.

체스판의 먼지를 털어내고 걸레로 닦으니 그럭저럭 쓸만한 체스판이 되었다. 하지만, 검정색 피스는 모두 있었으나, 흰색 피스는 개수가 올바르지 않았다.

체스는 총 16개의 피스를 사용하며, 킹 1개, 퀸 1개, 룩 2개, 비숍 2개, 나이트 2개, 폰 8개로 구성되어 있다.

동혁이가 발견한 흰색 피스의 개수가 주어졌을 때, 몇 개를 더하거나 빼야 올바른 세트가 되는지 구하는 프로그램을 작성하시오.


In [6]:
k,q,l,b,n,p = map(int,input().split())
k = 1 +- k
q = 1 +- q
l = 2 +- l
b = 2 +- b
n = 2 +- n 
p = 8 +- p
print(k,q,l,b,n,p)

1 0 0 0 0 1


In [1]:
# 또 다른 풀이1
# king, queen, rook, bishop, knight, pawn
chess_pieces = [1, 1, 2, 2, 2, 8]
pieces = list(map(int(chess_pieces)))
for i in range(len(chess_pieces)):
    print(chess_pieces[i] - pieces[i], end=' ')

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

### 백준 #2444

    ★              - 블랭크의 갯수 뽑아내기
   ★★★
  ★★★★★
 ★★★★★★★
★★★★★★★★★
 ★★★★★★★
  ★★★★★
   ★★★
    ★

In [3]:
N =  5
for i in range(N):
    line = ' '*(N - i - 1) + '*' * (2 * i + 1)
    print(line)
for i in range(1, N):
    line = ' ' * i + '*' * (2 * (N -i) -1)
    print(line)

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


### 백준 #1157
- 알파벳 대소문자로 된 단어가 주어지면 가장 많이 사용 된 알파벳이 무엇인지 알아내기.

In [4]:
alpha_dict = {}
string = 'A quick brown fox jumps over the lazy dog'
for i in range(26):
    c = chr(ord('a') + i)
    alpha_dict[c] = string.lower().count(c)
print(alpha_dict)

{'a': 2, 'b': 1, 'c': 1, 'd': 1, 'e': 2, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 1, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


In [6]:
alpha_items = list(alpha_dict.items())
alpha_items.sort(key=lambda x: x[1], reverse=True)
alpha_items[:5]

[('o', 4), ('a', 2), ('e', 2), ('r', 2), ('u', 2)]

### 백준 # 2738

In [ ]:
A = [[1, 1, 1],[2, 2 ,2],[3, 3, 3]]
B = [[3, 3, 3],[4, 4, 4],[5, 5, 100]]
C = []
for i in range(lan(A)):
    temp = []
    for k in range(len(A[i])):
        temp.append(A[i][k] + B[i][k])
    C.append(temp)

for i in range(len(C)):
    for k in range(len(C[i])):
         print(C[i][k], end=' ')
    print()



In [ ]:
# 선생님의 다른 풀이
C = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A)):
    for k in range(len(A[i])):
        C[i][k] = (A[i][k] + B[i][k])

for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

- numpy를 사용해야 하는 이유

In [7]:
import numpy as np
A = np.array([[1, 1, 1],[2, 2 ,2],[3, 3, 3]])
print(A)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [9]:
B = np.array([[3, 3, 3],[4, 4, 4],[5, 5, 100]])
print(B)

[[  3   3   3]
 [  4   4   4]
 [  5   5 100]]


In [10]:
# 백터화 연산
C = A + B
print(C)

[[  4   4   4]
 [  6   6   6]
 [  8   8 103]]
